### ISSUE TITLE
Find Volume from disk image

### ISSUE THREAD

**Issue by st3fan** [st3fan/ewm#129]
We set the `volume` field to 254. We should really determine it by looking at the DOS header of the disk image. How does that work in ProDOS?

**Comment by paulhagstrom** [comment]
This information is not included in .dsk format images at all (DOS or ProDOS), but exists in the address header to each sector. (This is why .nib format images are required if volume number is meaningful to the program.) Given this, there's no difference between DOS and ProDOS. It's in that 4+4 encoded area after D5AA96 (track, sector, volume, checksum) in the address field.

**Comment by st3fan** [comment]
@paulhagstrom On a DOS disk, the VTOC contains the volume id. See Beneath Apple DOS 4-2. Track 17, sector 0. I wonder if that can be used.
